[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
COMPANY_NAME=YAWA-BY-QLI

[internal]
; Internal WebRTC extension dialing
exten => _1XXX,1,NoOp(${COMPANY_NAME} WebRTC internal call from ${CALLERID(num)} to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,Hangup()

; Audio test extension
exten => 600,1,NoOp(${COMPANY_NAME} WebRTC audio playback test)
 same => n,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

; Echo test extension
exten => 601,1,NoOp(${COMPANY_NAME} WebRTC echo test)
 same => n,Answer()
 same => n,Echo()
 same => n,Hangup()